spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_store
    username: pet_store
    password: pet_store

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.boot: DEBUG
      pet.store.controller: DEBUG

  server:
    tomcat:
      accesslog:
        enabled: true
        pattern: "%h %l %u %t \"%r\" %s %b"
